JuliaPackaging/BinaryBuilderBase.jl

Project.toml, src/Prefix.jl, src/Sources.jl, test/sources.jl
Fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/845.  CC: @Keno
=> Do not follow symlinks by default for `DirectorySource`

.travis.yml, Artifacts.toml, Project.toml, src/Dependencies.jl, src/Prefix.jl, src/Rootfs.jl
X-ref: https://github.com/JuliaPackaging/Yggdrasil/pull/1487
=> Shard Bump

src/Sources.jl
Fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/888
=> Support tar archives compressed with Zstandard

src/UserNSRunner.jl
Fix error when running in `chroot`'ed environment and not all mount
points are visible.
=> Fix `is_ecryptfs()` when running in `chroot`.

src/Rootfs.jl
Otherwise this errors immediately in the wizard
=> Fix check for macOS compiler shard

.travis.yml, src/Runner.jl, test/runners.jl
=> [Runner] Fix LD_LIBRARY_PATH so we can run Fortran programs for host

Artifacts.toml, src/Rootfs.jl, src/Runner.jl
Bootstrapping had bitrotted a little bit, fix that and also rebuild PS
shards for aarch64-darwin so that CMake works.
=> Fix bootstrapping, rebuild PlatformSupport and GCC 11

src/Platforms.jl, src/Runner.jl
Loosely related to https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/975 and https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/976
=> Force hard-float ABI for 32-bit platforms

src/Rootfs.jl
If a build finishes quickly enough, unmounting can fail; let's just try again in those cases.
=> Try to unmount compiler shards a little bit more

Artifacts.toml, src/Rootfs.jl
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/2473
=> Add LLVMBoostrap 11.0.1

src/Sources.jl
Flexing a _tiny_ bit of `LibGit2`-fu, we can avoid expensive (and
race-triggering) `fetch()` calls on repositories that already contain
the hash we desire.
=> [GitSource]: Only `fetch()` if the repository doesn't contain the hash

src/ArchiveUtils.jl, test/compat.jl
Sounds like this should be ready? Should I add a callback for progress?
=> Switch back to Downloads.jl

Artifacts.toml, src/Runner.jl
x-ref: https://github.com/JuliaPackaging/Yggdrasil/pull/2795
=> Update Go shard to include gofmt

src/Prefix.jl, test/dependencies.jl
Attempt to fix the problem seen in https://github.com/JuliaRegistries/General/pull/34597
=> Use the proper destdir for cleanup_dependencies

.github/workflows/ci.yml
=> [CI] Delete `/opt` before installing Julia (not after)

Artifacts.toml, Project.toml, src/Rootfs.jl
Companion pull request in Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/3216
=> [Rootfs] Add LLVM 12

src/BuildToolchains.jl, src/Platforms.jl, src/Rootfs.jl, src/Runner.jl, src/utils.jl, test/platforms.jl, test/runners.jl
=> Shake out some assumptions about architecture of host platform

src/Platforms.jl
As observed in https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=15321&view=logs&jobId=f72a7361-53db-58d4-f33c-e019be7dac0f&j=572c5e49-83d5-5271-390a-e6dc77f89c6b&t=25aa3cdb-e20d-599e-657c-8776cc8a525f
=> Widen signature on parse_platform

src/Runner.jl
Not sure why I used the Rust names, and not having a way to reproduce the error
doesn't help.
=> [Runner] Fix name of Musl libc symlink

src/BinaryBuilderBase.jl, src/BuildToolchains.jl, src/DockerRunner.jl, src/Platforms.jl, src/Products.jl, src/Rootfs.jl, src/Runner.jl, src/UserNSRunner.jl, src/utils.jl, test/rootfs.jl, test/runners.jl
Over the last few weeks, from time to time I went through the errors reported by [`JET.jl`](https://github.com/aviatesk/JET.jl) with
```julia
JET.report_package(BinaryBuilderBase)
```
It isn't very easy, there are over 500 reported possible errors, lots of them from other packages, _many_ of them in `Base` or standard libraries.  With these changes I didn't observe any noticeable speedup, but I guess making some global variable constant and annotating some variables doesn't hurt anyway.  There are still plenty of errors to be fixed.
=> Some fixes suggested by JET

Project.toml, src/Rootfs.jl, test/rootfs.jl
Fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1135
=> [Rootfs] Promote experimental platforms to non-experimental

src/Runner.jl
With this I can build Enzyme for aarch64-apple-darwin without manual hacks, because
```console
% julia --compile=min -e 'using BinaryBuilderBase; BinaryBuilderBase.runshell(Platform("aarch64", "macos"))'
sandbox:${WORKSPACE} # echo $MACOSX_DEPLOYMENT_TARGET
11.0
```
=> [Runner] Set `MACOSX_DEPLOYMENT_TARGET` based on the actual macOS version

src/Runner.jl
On `aarch64-apple-darwin` currently we have
```console
sandbox:${WORKSPACE} # echo 'int main(){}' | gcc -x c -
clang-8: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11.0'
```
because `clang-8` isn't able to deal with version numbers ≥ 11.0 (I know,
right?).  This change sets `MACOSX_DEPLOYMENT_TARGET=10.16` for `as` on this
platform, to quickly work around the issue, similarly to what Apple does with
`SYSTEM_VERSION_COMPAT=1` (ref:
https://twitter.com/jeremyhu/status/1285230460402987008).
We might have to do similar things for other tools, but at the moment we are
aware of issues only for `as`.  For the record, `clang-8` for `as` is coming
from [`cctols`](https://github.com/JuliaPackaging/Yggdrasil/blob/dd0bfdabbaef3493841f54bce34539b270ebab8c/0_RootFS/gcc_common.jl#L153-L154 …
=> [Runner] Hot-fix for `as` wrapper

src/Prefix.jl
This function could be useful in other cases, I think it's better to take it out
from `get_addable_spec`.
=> [Prefix] Take out function to find the git commit SHA for given git tree hash

Artifacts.toml, src/Rootfs.jl
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/4486
=> [Rootfs] Update Go toolchain to v1.17.7

Project.toml, src/Prefix.jl, test/dependencies.jl
Fix https://github.com/JuliaPackaging/Yggdrasil/issues/4503.  CC: @eschnett @simeonschaub
=> [Prefix] Fix installation of dependencies from local directories

src/BuildToolchains.jl
This came up in https://github.com/JuliaPackaging/Yggdrasil/pull/4569
=> [BuildToolchains] Always set relevant host system CMake variables

Artifacts.toml, Project.toml, src/Runner.jl
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/4599
=> [RootFS] Add Rust toolchain v1.59.0

Artifacts.toml, src/Platforms.jl, src/Rootfs.jl, test/platforms.jl
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/4748
=> [Rootfs] Add LLVMBootstrap 13

Artifacts.toml, Project.toml, src/Rootfs.jl, test/rootfs.jl
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/4980
=> [Rootfs] Add GCC 12

Project.toml, src/Dependencies.jl, test/dependencies.jl
I quickly prepared this.  Still needs test and I have to see whether anything else is needed in BinaryBuilder (hopefully not).
CC: @vchuravy
=> [Dependencies] Define new `RuntimeDependency`

Artifacts.toml, Project.toml
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/5047
=> [RootFS] Add Rust toolchain v1.61.0

src/BuildToolchains.jl
Cmake was trying to use gcc with sanitizers enabled
=> Also make sanitizer use clang on cmake

src/Platforms.jl, src/Products.jl, src/Runner.jl
Like abi_agnostic, but only agnostic to the libgfortran etc ABIs,
not to the sanitizer ABI.
=> Add "libabi_agnostic"

Project.toml, src/ArchiveUtils.jl, test/archive_utils.jl
Thanks @haampie for the tip: <https://github.com/madler/pigz/issues/90#issuecomment-1125025224>.
=> [ArchiveUtils] Make tarballs compressed with `pigz` reproducible

Artifacts.toml
Reverts JuliaPackaging/BinaryBuilderBase.jl#273
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/4896#issuecomment-1257332314
=> Revert "[Rootfs] Add Rust v1.64.0"

Artifacts.toml
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/5761.  Need to wait for that one to be finished up.
=> [RootFS] Update build of GCC12

src/Products.jl
Fix https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/179, which I've just hit in a new recipe, reading https://docs.binarybuilder.org/stable/reference/#BinaryBuilderBase.LibraryProduct.
=> fix `dir_paths` kwarg -> arg

src/BinaryBuilderBase.jl
Companion to <https://github.com/JuliaCI/sandboxed-buildkite-agent/pull/47> and
<https://github.com/JuliaPackaging/Yggdrasil/pull/6261>.
=> Add environment variable for setting ccache directory

src/Prefix.jl, src/Sources.jl, test/sources.jl
=> Unzip and untar .conda packages

src/Dependencies.jl, test/dependencies.jl
Ref: https://github.com/JuliaRegistries/General/pull/79224
=> [Dependencies] Propagate compat of `RuntimeDependency`

Artifacts.toml
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/6774.  Fix #307.
=> [RootFS] Add Rust toolchain v1.69.0

Artifacts.toml, src/Rootfs.jl, src/Runner.jl, test/runners.jl
This fixes #290 and fixes #248
=> Add clang-16

Artifacts.toml, Project.toml
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/7524
=> [RootFS] Add Rust 1.73.0

src/BuildToolchains.jl, src/Runner.jl
I'm not really in love of how this is getting, I think a nice refactor might be to move all these gcc versions/platform to a toolchain struct that has everything in it. But for now this is an attempt
=> Make lld more first party in BBB

.github/workflows/ci.yml, test/dependencies.jl
While we find a proper solution, don't make tests hard fail.
Ref: #358.
=> Work around test failure in Julia nightly

.github/workflows/ci.yml, src/Sources.jl
This was broken by https://github.com/timholy/ProgressMeter.jl/pull/304.
=> [Sources] Explicit conversion to work around breaking change in ProgressMeter

Project.toml
=> Release 1.30

Artifacts.toml
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/9267
=> [RootFS] Add Go v1.23.0

Artifacts.toml, Project.toml, src/Rootfs.jl, test/rootfs.jl
Accompanying Yggdrasil PR: https://github.com/JuliaPackaging/Yggdrasil/pull/9220
I'll flip this out of draft mode once all compilers have been built.
=> Add support for FreeBSD AArch64

Artifacts.toml, Project.toml
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/9415
cc @ararslan @giordano
=> Add bootstrap artifacts for LLVM 18.

src/Runner.jl
Reported in https://github.com/JuliaPackaging/Yggdrasil/pull/10360#discussion_r1935608177, but I don't have a reproducer for a test.
=> [Runner] Add new dir to headers search path on aarch64-freebsd

Artifacts.toml
Ref https://github.com/JuliaPackaging/Yggdrasil/pull/11427
=> Add RustToolchain v1.87

Artifacts.toml, src/Runner.jl
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/11828.  Fix https://github.com/JuliaPackaging/Yggdrasil/issues/4067.
=> [RootFS] New PlatformSupport artifacts without old MinGW headers

src/Runner.jl
=> [Runner] Fix condition under which the ccache volume is mounted
