JuliaPackaging/BinaryBuilderBase.jl

- src/DockerRunner.jl
- src/Platforms.jl
- src/Rootfs.jl
- src/Runner.jl
- src/UserNSRunner.jl
- test/platforms.jl
- test/rootfs.jl
- test/runners.jl
This is still very much work in progress
Still to do:
* It would be great to issue a warning if we're building for an higher instruction sets, but none (or very few?) of those instructions are used, so to avoid building useless stuff
> Add support for architectures in the wrappers

- Project.toml
- src/BinaryBuilderBase.jl
- src/Rootfs.jl
> Touch a file to indicate that user accepts to download macOS SDK

- src/Products.jl
The at-ref currently causes a documentation build warning because Documenter can't resolve it. This is true both in the BinaryBuilderBase docs (doesn't know anything about `build_tarballs`), but also in BinaryBuilder docs (which includes BinaryBuilderBase docstrings too; `build_tarballs` of course exists, but Documenter still can't resolve it because it's in a different package).
> Remove at-ref to BinaryBuilder.build_tarballs

- src/Prefix.jl
- test/sources.jl
I was running into an issue when my sources were just two `DirectorySources`, something like this:
```julia
sources = [
DirectorySource("./src"), # should become ${WORKSPACE}/srcdir
DirectorySource("./mysubdir", target="mysubdir"), # should become ${WORKSPACE}/srcdir/mysubdir
]
```
`build_tarballs` would then fail when it's copying over the second one with an exception on line 308, because it tries to copy into a non-existing directory.
Don't really know if this is the correct solution, or maybe my `sources` setup is just wrong, but it seems to work for me (TM).
> mkdir target directory when copying for DirectorySource

- src/Runner.jl
I've looked into automatically determining the version of glibc a few times, but never found a general solution (only something that would work for `x86_64-linux-gnu`).  However some build systems insist on getting the version of glibc with `getconf GNU_LIBC_VERSION`, which however doesn't work, see for example https://github.com/SCIP-Interfaces/SCIP.jl/issues/165.  My proposal is to have an environment variable that at least gives the same result.  I guess someone might suggest to have a `getconf` script in the rootfs which simply does `echo ${@}`
> Add `GNU_LIBC_VERSION` to the mappings of the build environment

- deps/.gitignore
- src/Runner.jl
`-D` causes `ar` to not embed timestamps, UIDs, etc... into static archives.
> Small reproducibility improvement

- src/Products.jl
- test/products.jl
This will be more extensible in the future; it always makes me a little uncomfortable to have things like `func(arg1, arg2$(maybe_arg3)` where `maybe_arg3` has the comma embedded within it.
> Default to more explicit `dlopen_flags_str()`.

- src/Runner.jl
This fixes meson having a hard time running `ar --version`
> Don't try to fix up double-dashed commands in `ar` like `--version`

- src/Runner.jl
This avoids the issue of `Base.have_color` now being able to be
`nothing` in Julia `v1.5`.
> Switch `Base.have_color` to `get(stdout, :color, false)`

- Artifacts.toml
These rebuilt shards fix the following problems:
* `with-arch` was not actually set, despite claims to the contrary.  Because the only users complaining about these issues are on Linux and FreeBSD, we are only rebuilding these shards right now, pending future issues that will no doubt be coming soon.
* `x86_64-linux-musl` lacked a patch that fixed include paths for C++ code on GCC 6+.
> Bump x86_64-linux-gnu, x86_64-linux-musl and x86_64-unknown-freebsd11.1 shards

- src/Rootfs.jl
- src/Runner.jl
See individual commits - just some prepratory work for adding https://github.com/JuliaPackaging/Yggdrasil/pull/1626 as a compiler shard.
> Prepratory work for Darwin Aarch64 shard

- Artifacts.toml
- src/Rootfs.jl
The plan is to not upload these, but make them available manually
on arctic3 and to people who want to work on Darwin Aarch64 support
until the SDK becomes publicly available.
> Add artifacts for iains gcc branch

- src/Platforms.jl
- src/Runner.jl
This fixes an issue with `install_name_tool` not being able to fix rpath of some
ICU libraries for macOS, see
https://github.com/JuliaPackaging/Yggdrasil/issues/1668 and
https://github.com/JuliaPackaging/Yggdrasil/issues/1650#issuecomment-691369425
for reference.
I'm not 100% sure whether we should always enable it or an case-by-case basis, like https://github.com/JuliaPackaging/Yggdrasil/pull/1670.  Homebrew used to use this flag as well in an old version: https://github.com/Homebrew/legacy-homebrew/commit/585d7c6e650f18820092f263d0e20cfae730f5c1, but I can't find whether it's currently used by default.
> Pass `-headerpad_max_install_names` to macOS linker

- src/Rootfs.jl
- test/rootfs.jl
I'm not entirely sure this is a desirable feature because I think it'd make stuff like [`contrib/refresh_bb_tarballs.sh`](https://github.com/JuliaLang/julia/blob/eeffe578534289e4e99f72db263564173188b052/contrib/refresh_bb_tarballs.sh) more complicated.  However, in principle I believe this is a good thing to do, since when building for FreeBSD and macOS we usually don't link to libstdc++, and auditor would yell at us if there is something wrong.  I'm also happy to default `skip_freebsd_macos` to `false`
> Add keyword to `expand_cxxstring_abis` to skip FreeBSD and MacOS

- src/Dependencies.jl
- src/Prefix.jl
- test/dependencies.jl
This PR adds two things; first, usage of a new `Pkg` API to decouple
version resolution from constraints upon the currently-running version of
Julia, and the ability to set a version to be used at build-time that is
independent of the compat entries we will put into the generated JLL's
`Project.toml`.
> Unshackle build-time dependency resolution from Pkg.Resolve

- src/Rootfs.jl
- test/rootfs.jl
Let the user pass a custom function to selectively skip expansion
I believe this is also better than hardcoding FreeBSD and macOS in the name of the argument.
> More flexible skipping of C++ string ABIs expansion

- Manifest.toml
- src/Prefix.jl
Create the context after activating the temporary environment, otherwise we'd be
using the global one.
Fix #47.
> Add dependencies using the build environment instead of the global one

- src/Dependencies.jl
- test/dependencies.jl
> Fix JSON serialization for Dependency with build_version

- src/Rootfs.jl
- test/compat.jl
This will make it easier to have base julia deps always build for the
widest possible set of platforms, while letting the rest of Yggdrasil
continue to live in blissful ignorance
> Add `experimental` kwarg to `supported_platforms()`

- test/dependencies.jl
All JLL packages formally depends on `Pkg`, including the new ones that don't
actually load it.  However, in Julia nightly `Pkg` has an indirect dependency on
`LibCURL_jll` and `MozillaCACerts_jll`, which means that `installed_jlls` in
`setup_dependencies` _always_ contains these two packages, see
https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/c4c7c838ad8cc2b134d0a46551497ef92f9a9e68/src/Prefix.jl#L411-L414
This changeset is to temporarily ignore the failing tests, for the sake of
keeping the test suite working, until this is properly resolved.
CC: @staticfloat
> Mark currently broken tests as such

- .travis.yml
- src/ArchiveUtils.jl
- src/Sources.jl
- test/compat.jl
- test/sources.jl
Fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/928
> Do not download again sources that are already cached

- src/Rootfs.jl
- test/rootfs.jl
Because we only have GCC 11 available, we need to ensure that we only
expand to `libgfortran5` on aarch64 MacOS
> Limit `libgfortran` expansion on `aarch64-apple-darwin`

- src/Platforms.jl
- test/rootfs.jl
Before, we used -march=i686, but that does not include MMX, SSE, SSE2 support,
which Julia requires. By switching to pentium4 as base level, better optimized
code can be generated, and also linking against libjulia then work for
32bit binaries without extra compiler flags.
Alternative to https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/960, see also the discussion there.
At least I hope this is a viable alternative -- I didn't test it thoroughly to verify.
> Switch platform arch i686 to use -march=pentium4

- .travis.yml
Restoring the cache seems to take forever.  We could use `travis_wait`
to avoid the 10-minute timeout, but it just takes too long.
> [Travis] Do not run full test suite without SquashFS

- Artifacts.toml
- src/Rootfs.jl
@giordano so the end of the investigation is that the version of GCC 11 that it was based off of is just broken in its C++ header searching, so I have decided instead to just jam a host GCC 9 together with the aarch64-darwin GCC 11 shard, which should be fine.
> Update aarch64 compiler, add workaround for broken host GCC v11

- src/Rootfs.jl
- src/Runner.jl
I originally wanted to add the ability for the `os_version` tag in the
target to change things automatically, but we need to slightly update
the compiler shards first (e.g. remove the `14` from the paths in the
compiler shard and whatnot).
> Pass `-mmacosx-version-min` on `clang` as well as `gcc`

- Artifacts.toml
- src/Rootfs.jl
- src/Runner.jl
Also strips out a lot of the Rust special-casing due to a previous
limitation of `rustc` being unable to self-host on `x86_64-linux-musl`.
This has since been fixed, and we are no longer forced to mount in
`x86_64-linux-gnu` support libraries just to run the `rustc` compiler.
Huzzah!
> [Rust] upgrade to v1.48.0

- src/Runner.jl
Ref https://github.com/JuliaPackaging/Yggdrasil/pull/2148 and
https://github.com/JuliaPackaging/Yggdrasil/pull/2168.
> [Runner] Create symlinks to work around issues in Rust toolchain

- src/BinaryBuilderBase.jl
- src/BuildToolchains.jl
- src/DockerRunner.jl
- src/Rootfs.jl
- src/Runner.jl
- src/UserNSRunner.jl
- src/utils.jl
- test/platforms.jl
- test/rootfs.jl
- test/runners.jl
This allows us to better discriminate between the wrappers for the host and
those for the target, important when the two platforms are similar (e.g., they
differ only by the C++ string ABI).
With this PR I can build https://github.com/JuliaPackaging/Yggdrasil/pull/2157 for `x86_64-linux-musl-cxx03` without any change.  Fix #81.
> [Runner] Move target wrappers to `/opt/bin/$(triplet(platform))`

- Artifacts.toml
- src/Rootfs.jl
- src/Runner.jl
This is required because of a regression in the `Rust` build on
i686-w64-mingw32: https://github.com/rust-lang/rust/issues/79609
> Roll `Rust` build back to `v1.43`

- .github/workflows/ci.yml
This lets us keep testing development of the package until we can use again
`master` or `release-1.6`.
> [GHA] Temporarily use an older version of Julia for testing

- src/Products.jl
- test/products.jl
Also improve docstrings of products, they were severely out-of-date, and the
most useful parts (the docstrings attached to the inner constructors) were
basically inaccessible.
This goes together with
https://github.com/JuliaPackaging/JLLWrappers.jl/pull/24.
> [Products] Print `nothing` as dlopen flags for libraries not to dlopen

- Artifacts.toml
- src/Rootfs.jl
- test/rootfs.jl
To review together with https://github.com/JuliaPackaging/Yggdrasil/pull/2301.
TODO:
> Add GCC 10

- src/Dependencies.jl
- test/dependencies.jl
This changes `Dependency` objects to always (?) store a full `VersionSpec`, not just a `VersionNumber`, and (de)serialize that properly.  Fixes #89 (well, I hope).
Before this, https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/981 should be merged.
CC @benlorenz @thofma
> Properly (de)serialize VersionSpec to JSON

- src/Dependencies.jl
- test/dependencies.jl
Reverts JuliaPackaging/BinaryBuilderBase.jl#93.  It breaks registration of LLVM: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=8363&view=logs&j=82ede541-d8dc-5eb8-fd6b-5903678e9282&t=31eefa9e-75b0-5107-6058-36e5c2f2fd84
```
Updating registry at `/depot/registries/General`
Downloading sources...
ERROR: LoadError: KeyError: key "ranges" not found
Stacktrace:
[1] getindex
@ ./dict.jl:482 [inlined]
[2] dejson(#unused#::Type{Pkg.Types.VersionSpec}, d::Dict{String, Any})
@ BinaryBuilderBase /depot/packages/BinaryBuilderBase/OykWl/src/Dependencies.jl:130
[3] dependencify(d::Dict{String, Any})
@ BinaryBuilderBase /depot/packages/BinaryBuilderBase/OykWl/src/Dependencies.jl:138
[4] _broadcast_getindex_evalf
@ ./broadcast.jl:648 [inlined]
[5] _broadcast_getindex
@ …
```
> Revert "Properly (de)serialize VersionSpec to JSON"

- Artifacts.toml
- src/Rootfs.jl
Most notable new features:
* it has `samurai` instead of `ninja` (and `apk`
commands don't break anymore)
* a new version of `apk` is installed.  The `apk` command is a wrapper which
always pass the option `--no-chown`
* new Cargo build test in the test suite
Companion PR in Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/2356.
> [Rootfs] Add new version of Rootfs

- Artifacts.toml
We backported the patch for a GCC bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87467.  For reference, see also
https://github.com/JuliaPackaging/Yggdrasil/issues/2389.
Companion PR in Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/2415.  CC: @omus
> New x86_64 GCC shards with fixed AVX512 intrinsics

- Artifacts.toml
- src/Runner.jl
Our MacOS shards are now providing `dsymutil` as the primary name, so
just use that instead.
> Fix MacOS GCC shards

- src/Dependencies.jl
- src/Prefix.jl
- src/Runner.jl
- test/dependencies.jl
- test/sources.jl
Main changes:
* we now have two "prefixes", one for the target and one for the host.  To
implement this,
* `setup_workspace` takes in input the platforms of the target and the host,
and it creates the symlink
`/workspace/destdir` -> `/workspace/TARGET_TRIPLET/destdir`
* the user will call `setup_dependencies` twice, once for the host and once
for the target
* a new helper function `destdir(prefix, platform)` gives consistently the path
to the destdir for the given platform within the given prefix
* added relevant environment variables `host_*dir` in the runners, and add
`host_bindir` to the `PATH`
* added `is_host_dependency`, `is_target_dependency`, `is_build_dependency`,
`is_runtime_dependency` functions which are _very_ useful to filter
dependencies in different situations: as we add …
> Add HostBuildDependency

- Manifest.toml
- Project.toml
- src/ArchiveUtils.jl
- src/Prefix.jl
Fixes https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/106. Using `pigz` allows us to perform fast Gzip compression. In the future we should probably switch to the `7z` or `zstd` format.
> Use `pigz` to create archives

- Artifacts.toml
- src/Rootfs.jl
I believe I did this correctly but as I had some issues building these I want to do some additional verification. 
Associated Yggdrasil release: https://github.com/JuliaPackaging/Yggdrasil/releases/tag/PlatformSupport-v2021.1.28
Introduces PlatformSupport artifacts for `aarch64-apple-darwin20` and `i686-linux-musleabihf`.
> Rebuild PlatformSupport 2021.1.28

- Artifacts.toml
Adds the first public GCC/PlatformSupport shards for Apple Silicon. For reference, see https://github.com/JuliaPackaging/Yggdrasil/pull/2436
Should I remove the `PlatformSupport-aarch64-apple-darwin20.v2020.11.6.x86_64-linux-musl.*` entries which contain no download?
> Initial aarch64-apple-darwin20 GCC/PlatformSupport shards

- src/ArchiveUtils.jl
- src/Prefix.jl
- test/archive_utils.jl
- test/runtests.jl
While building a new GCCBootstrap I noticed that `7z` was being used for compressing the "unpacked" artifact. As the original point of [using `pigz`](https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/107) was to improve the compression time when building shards I tracked this down and found this [call to `archive_artifact` in Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil/blob/2fba739eec6d70724d6594a4e5c011fc872cc8e8/0_RootFS/common.jl#L48). In order to fix this I could revise Yggdrasil to use `_archive_artifact` but since this custom version of `archive_artifact` will be used beyond just BinaryBuilderBase I thought it best to clean up the interface first.
Additionally, I used this PR to add support for compressing artifacts in the `xz` format as discussed in …
> Refactor pigz support

- src/UserNSRunner.jl
As discussed with @staticfloat and @giordano on Slack (https://julialang.slack.com/archives/C674ELDNX/p1613895520011000?thread_ts=1613741887.479600&cid=C674ELDNX).
The purpose is to avoid problems on systems where specific nameserver settings are applied in `/etc/resolv.conf`. In this case it makes sense to use the local `/etc/resolv.conf`, e.g., if the default DNS servers used by `BinaryBuilderBase` (Google's DNS servers) are not reachable from within the local network.
I have tested this locally on an Ubuntu machine and it fixed the issue I had with unreachable Google DNS servers, but I have not been able to test it on non-Ubuntu systems.
@staticfloat Is this implementation what you had in mind? One downside of the current approach is that `/etc/resolv.conf` is not editable anymore, …
> Mount existing `/etc/resolv.conf` in `UserNSRunner` if it has nameserver settings

- src/BuildToolchains.jl
Fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1027
> [BuildToolchains] Fix name of CMake variables

- src/Rootfs.jl
`expand_cxxstring_abis(ps::Vector{<:Platform}; kwargs...)` should be expanded to `expand_cxxstring_abis(ps::Vector{<:AbstractPlatform}; kwargs...)` to match the scalar version of `expand_cxxstring_abis(platform::AbstractPlatform; skip=Sys.isbsd)`
> expand_cxxstring_abis(Vector{<:AbstractPlatform})

- src/Runner.jl
The variable is inherit from the host, but some tools (like [GDB](https://sourceware.org/gdb/onlinedocs/gdb/Environment.html)) expect the
variable to be set to the actual shell used inside the build environment.
> [Runner] Set `SHELL` environment variable inside the runner

- Artifacts.toml
- src/Rootfs.jl
xref: https://github.com/JuliaPackaging/Yggdrasil/pull/2781
> Update Go shard to 1.16.3

- Artifacts.toml
- src/Runner.jl
Our GCC shards did not correctly configure themselves to target the
oldest supported macOS build.  Instead, because GCC doesn't fully
understand how to use the availability macros that macOS uses, it
assumed that it was able to use `clock_gettime()`, which caused a
reliance on that symbol within `libgfortran` itself.  This resulted in
our CSL being unusable on macOS 10.11 and earlier.  This PR updates the
GCC shards [0] and also adds compiler flags to enforce that users who
attempt to use `gcc` on macOS do not end up making the same mistake.
[0] https://github.com/JuliaPackaging/Yggdrasil/pull/2836
> Fix `clock_gettime` errors on old macOS machines

- src/Runner.jl
This may be needed to run tools included in a HostBuildDependency,
as in Qt6.
See also https://github.com/JuliaPackaging/Yggdrasil/pull/2856#discussion_r615287341
> Add host_libdir to the LD_LIBRARY_PATH

- .github/workflows/ci.yml
- Project.toml
- src/Runner.jl
- test/runners.jl
> Add protection from double `--target` specification in `rustc` wrapper

- Artifacts.toml
X-ref: https://github.com/JuliaPackaging/Yggdrasil/pull/2901
> Update `GCCBoostrap` on macOS to avoid `mkostemp`

- src/Runner.jl
Ref: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/134#discussion_r628797539
> [Runner] Set `_DARWIN_FEATURE_CLOCK_GETTIME` macro only for macOS

- Project.toml
- src/Prefix.jl
- src/utils.jl
- test/prefix.jl
Companion pull request in `BinaryBuilder`: https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1059
> [Prefix] Add `subdir` argument to `logdir` function

- Project.toml
- src/BuildToolchains.jl
- src/Runner.jl
We can't make the Objective-C compiler always be the same as
`clang -x objective-c` because this won't work when using the compiler as linker: when
specifying the language with `-x <LANG>` the input files are assumed to always
be plain text source code files, but you pass object files to the linker.
This changeset removes the `objc` wrapper, which was created solely with the
goal to build Glib with Meson (which we never managed to do so far anyways) and
instead sets in the Meson toolchain file the Objective-C compiler to `cc` and
passes `-x objective-c` only when compiling but not linking.  This is more
correct and less error-prone than what we have now.
We also automatically add `-I${includedir}` and `-L{libdir}` for all languages
in the Meson toolchain file, to avoid having to manually …
> Reorganise Objective-C wrapper and Meson toolchain file

- Project.toml
- src/Dependencies.jl
- test/dependencies.jl
In a `Dependency` we have to specify two versions numbers: the actual build
version and the compat version, which 99.99% of the time are the same.  This is
annoying and error-prone.  With this change the build version defaults to the
minimum compatible version specified by `compat`, if any.
CC: @fingolfin
> [Dependencies] Default `build_version` to the minimum compatible version

- src/Prefix.jl
- src/compat.jl
- test/compat.jl
`strip_backslash` was a misnomer: what we remove is a forward slash, not a
backward one.  "Path separator" is more accurate though.
> Rename helper function `strip_backslash` -> `strip_path_separator`

- Artifacts.toml
- Project.toml
- src/Rootfs.jl
- test/rootfs.jl
Companion pull request in Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/3174
> [Rootfs] Add GCC 11.1

- src/Prefix.jl
- test/prefix.jl
A way to test this is to have the following dependencies:
```julia
dependencies = [
Dependency("Libuuid_jll", v"2.34"),
Dependency("Libmount_jll", v"2.34"),
]
```
The two artifacts have dozens of clashing files (all `share/locale/*/LC_MESSAGES/util-linux.mo`), but for the same version of the packages they are the same.
> [Prefix] Do not show warning if clashing files are the same

- Project.toml
- src/Rootfs.jl
- test/rootfs.jl
LLVMBootstrap 12 needs to be built with GCCBootstrap ≥ 7.  However, when
building for FreeBSD with LLVMBootstrap 12 we can't use `ld` from binutils <
2.26 (which corresponds to GCCBootstrap < 6) to link some object files.  The
solution is to not allow old GCCBootstrap with new versions of LLVMBootstrap for
FreeBSD.
For reference see #158.
> [Rootfs] Do not use old GCC versions with new LLVM for FreeBSD

- Project.toml
- src/Runner.jl
- test/runners.jl
When compiling with GCC this makes sure its libraries have precedence over
anything else, in particular other compiler libraries that may be elsewhere, for
example `CompilerSupportLibraries_jll` used as dependency during the build.
Fix #163.
Note: I ran the tests of BinaryBuilder on this branch in https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1032, seems all good.
> [Runner] Push `/opt/${target}/${target}/lib{,64}` to linker search path

- Artifacts.toml
- src/Rootfs.jl
Companion pull request in Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/3321.
This is needed for #157, because we need a much newer CSL to (hopefully) make things work.
Note: I didn't upgrade the base image to Alpine v3.13 or v3.14, any opinions
about that?
> [Rootfs] Update to new build

- Artifacts.toml
- Project.toml
- src/Rootfs.jl
- src/Runner.jl
- test/runners.jl
This should make it easier to run applications we build with the host toolchain.  CC: @vchuravy
> [Runner] Move `csl_paths(host_platform)` at the beginning of `LD_LIBRARY_PATH`

- Project.toml
As far as I know, #166 is technically a breaking change, as it removes FreeBSD 11 artifacts. Thus we would need to tag a breaking release anyway, but if we're going to do that, we'd might as well tag 1.0 given the general stability of BBB. Thoughts?
> Set version to 1.0.0

- src/Runner.jl
As far as I know, binutils tools come from the GCCBootstrap, so they aren't
available if the C compiler is not requested.
[Ignore whitespaces](https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/168/files?w=1) for a slightly easier to read diff.
> Do not generate wrappers for tools that don't exist

- src/Products.jl
- test/products.jl
This PR adds an `isless` method for comparing `ExecutableProduct` and `LibraryProduct` such that `ExecutableProduct`s always come before `LibraryProduct`s. This is in support of https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1109. This seemed like the more appropriate repo to add this particular method compared to regular `BinaryBuilder`
Example Input:
```
#from https://github.com/JuliaPackaging/Yggdrasil/blob/master/U/unixODBC/build_tarballs.jl
products = [
LibraryProduct("libodbc", :libodbc),
ExecutableProduct("odbc_config", :odbc_config),
LibraryProduct("libodbcinst", :libodbcinst),
ExecutableProduct("isql", :isql),
ExecutableProduct("iusql", :iusql),
ExecutableProduct("odbcinst", :odbcinst),
LibraryProduct("libodbccr", :libodbccr),
ExecutableProduct("slencheck", …
```
> add Base.isless for ordering ExecutableProduct vs LibraryProduct

- .github/workflows/ci.yml
- src/Prefix.jl
Since we're doing the symlinking now, there's no reason not to just
have BinaryBuilderBase manage this directory and clear it out if it
already exists. This avoids having to manually clear out existing
directories in `bb add`.
> Clear out artifacts destdir path if it already exists

- .github/workflows/ci.yml
- Project.toml
- src/DockerRunner.jl
- src/UserNSRunner.jl
- test/runners.jl
> [Runners] Do not generate toolchain files if we are bootstrapping

- Artifacts.toml
- Project.toml
- src/BuildToolchains.jl
- src/DockerRunner.jl
- src/Rootfs.jl
- src/Runner.jl
- src/UserNSRunner.jl
- test/rootfs.jl
This will replace the file we currently hard-code in the Rust compiler shard.
PR to update Rust toolchain build script: https://github.com/JuliaPackaging/Yggdrasil/pull/3992
> Upgrade Rust to v1.57.0 and JIT-generate Cargo config file

- Project.toml
- src/Rootfs.jl
Also `PlatformSupport` calls the armv6l artifacts `armv7l`
> [Rootfs] Fix name of PlatformSupport artifacts

- src/BuildToolchains.jl
- src/DockerRunner.jl
- src/Runner.jl
- src/UserNSRunner.jl
I don't understand why we were forcing `gcc`, on `aarch64-apple-darwin` this
causes lots of trouble, because Cargo would pass in the argument `-arch arm64`
which isn't accepted by GCC, but it is by LLVM.
Now that we can JIT-generate the file, write the config only for host and target
platforms, we don't have the toolchains for the other platforms anyway.
Additionally, remove some workarounds previously added in `Runner.jl` to fix
errors in the old static config file.
> [BuildToolchains] Use `<aatriplet>-cc` as linker in Cargo config

- src/DockerRunner.jl
- src/Runner.jl
- src/UserNSRunner.jl
- test/runners.jl
We have lots of duplication between `UserNSRunner.jl` and `DockerRunner.jl`,
this should reduce it quite a lot and make further additions to the setup less
error-prone.
> [Runner] Define a function to set up runner constructors

- Project.toml
- src/Runner.jl
Address #188 before rebuilding all the GCC compiler shards for Musl.
With this PR:
```console
% julia-16 -e 'using BinaryBuilderBase; BinaryBuilderBase.runshell(Platform("aarch64", "linux"; libc="musl"))'
sandbox:${WORKSPACE} # ls -l /opt/${target}/${target}/sys-root/usr/lib/
total 15361
-r--r--r--    1 root     root          5320 Oct 21  2020 Scrt1.o
-r--r--r--    1 root     root          5120 Oct 21  2020 crt1.o
-r--r--r--    1 root     root          1072 Oct 21  2020 crti.o
-r--r--r--    1 root     root          1012 Oct 21  2020 crtn.o
-r--r--r--    1 root     root      11614452 Oct 21  2020 libc.a
lrwxrwxrwx    1 root     root             7 Dec  5 14:19 libc.musl-aarch64.so.1 -> libc.so
-r-xr-xr-x    1 root     root       4082299 Oct 21  2020 libc.so
-r--r--r--    1 root     root …
```
> [Runner] Add hot-fix to symlink `libc.musl-<ARCH>.so.1` -> `libc.so`

- Project.toml
- src/Dependencies.jl
- src/Platforms.jl
- test/dependencies.jl
- test/platforms.jl
This let us declare that certain dependencies are needed at build/runtime only
on some platforms.
First part to address #174, next part will be in BinaryBuilder (I have a somewhat working version locally, but need to figure out a couple of things not working as expected).  Opening as draft for the time being to ask for feedback, especially about names (I'm not really fond of the name `filter_platforms`, which is also used for both the field and the function to filter the vector of dependencies).  After settling on names and API I'll add documentation and tests.
You can find a first proof-of-concept at https://github.com/giordano/NativeFileDialog_jll.jl (note: I'll probably delete the repo after this work is done).  You can see that GTK3_jll is in the …
> Add field to dependencies to filter them by platform

- src/DockerRunner.jl
- src/UserNSRunner.jl
```jl
julia> io = IOBuffer();
julia> run(pipeline(`echo hello`; stdout=io))
Process(`echo hello`, ProcessExited(0))
julia> String(take!(io))
"hello\n"
```
> simplify `run_interactive`, `pipeline` can now accept an `IOBuffer`

- src/DockerRunner.jl
- src/UserNSRunner.jl
Reverts JuliaPackaging/BinaryBuilderBase.jl#197
This caused some issues (and we need some more tests for this apparently).
> Revert "simplify `run_interactive`, `pipeline` can now accept an `IOBuffer`"

- Project.toml
- src/DockerRunner.jl
- src/Runner.jl
- src/UserNSRunner.jl
- test/runners.jl
Fixes https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/197#issuecomment-1003012107
> fix output from runners to IOBuffer

- src/Prefix.jl
Probably a cruft from `BinaryProvider` times: https://github.com/JuliaPackaging/BinaryProvider.jl/blob/55aeaea2652c1b43ba882c2f833196e99f10e2db/src/Prefix.jl#L64-L66
> [Prefix] Remove unused `global_prefix` variable

- src/Runner.jl
With this I get:
```console
% julia-16 -e 'using BinaryBuilderBase; BinaryBuilderBase.runshell(Platform("aarch64", "macos"))'
sandbox:${WORKSPACE} # export SUPER_VERBOSE=1
sandbox:${WORKSPACE} # cc --version
ccache /opt/x86_64-linux-musl/bin/clang -target arm64-apple-darwin20 --sysroot=/opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root -march=armv8-a -mtune=cortex-a57 -nostdinc++ -isystem /opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root/usr/include/c++/v1 -Wno-unused-command-line-argument -mmacosx-version-min=11.0 --version -L/opt/aarch64-apple-darwin20/aarch64-apple-darwin20/lib -fuse-ld=aarch64-apple-darwin20 -headerpad_max_install_names
clang version 12.0.0 (/home/mose/.julia/dev/BinaryBuilderBase/deps/downloads/llvm-project.git …
```
> [Runner] Set `-mmacosx-version-min` based on the actual macOS version

- src/Rootfs.jl
This PR adds a function `installed_shards()` that outputs a vector of `CompilerShard`s that are currently download and installed on a user's system using the stdlib `Artifacts.artifact_exists()`.
I ran into two situations where this could be useful
1. I downloaded many OS/CompilerVersion shards doing one-off testing and filled up my hard drive. Having this, I would be able to reference which shards I know I use consistently vs ones that could be deleted (still have to manually search and delete).
2. The [Artifact.toml](https://github.com/JuliaPackaging/BinaryBuilderBase.jl/commit/46437bea72d02e5186d16f215b125cd004f52c84) for BBB gets updated and I am trying to see if I have an old version downloaded or the newest version.
Things this can't do:
If the BBB `Artifact.toml` is updated, this …
> add installed_shards() function to output downloaded artifacts on system

- src/BinaryBuilderBase.jl
We weren't accessing `runner_override[]` correctly, so
```julia
runner_override == "privileged"
```
always evaluated to `false`.
Bug introduced by #196.
> Fix setting of `use_squashfs` with privileged runner

- src/Prefix.jl
Ref:
* https://github.com/JuliaPackaging/Yggdrasil/pull/4289#discussion_r788272404
* https://github.com/JuliaPackaging/Yggdrasil/pull/4294#issuecomment-1018273769
> [Prefix] Remove assumption that URL of GitSource must end with `.git`

- src/Runner.jl
With these two simple scripts I'm able to compile for macOS `licensecheck` without [this manual hack](https://github.com/JuliaPackaging/Yggdrasil/blob/2b0395821db522fa190e749d4d7fd670a5297643/L/licensecheck/build_tarballs.jl#L17-L24), and LLVM 13.0.1 from https://github.com/JuliaPackaging/Yggdrasil/pull/4403 without having to manually create a fake `sw_vers`
> [Runner] Generate some fake XCode tools which are occasionally needed

- Manifest.toml
- src/Runner.jl
- test/dependencies.jl
- test/runners.jl
For platforms which are DockerRunner supported, use `x86_64` as the `default_host_platform` architecture.
> Fix architecture of `default_host_platform` to `x86_64`

- src/Rootfs.jl
This opens up the door to keeping in a maintainable way multiple versions of the
Go and Rust toolchains.
> [Rootfs] Automatically get list of available Go and Rust toolchains

- src/Prefix.jl
- test/dependencies.jl
With Julia v1.9 we have to use `Pkg.respect_sysimage_versions(false)` to install
stdlib JLLs in our projects.
Opening as draft because tests are failing anyway for me even with this change, but I don't have the time to debug now.
> [Prefix] Fix installation of packages in nightly

- src/Runner.jl
Currently several JLLs need to manually add `-I${includedir}` to their
CPPFLAGS in order to build correctly on FreeBSD. Fix this by adjusting
the clang wrapper.
See https://github.com/JuliaPackaging/Yggdrasil/issues/3949
> Add `-isystem ${includedir}` for clang on FreeBSD, and GCC on musl 

- Artifacts.toml
- src/Rootfs.jl
- test/rootfs.jl
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/4551.  See also https://github.com/JuliaPackaging/Yggdrasil/pull/4547.
> [Rootfs] Update RootFS and GCC version for aarch64-apple-darwin

- Project.toml
- src/Rootfs.jl
- test/rootfs.jl
Add a positional argument to select the microarchitectures to expand, and a
keyword argument to select the platforms to expand.  This should provide a
flexible interface to limit the expansion and avoid building for many useless
platforms.
> [Rootfs] Improve API of `expand_microarchitectures`

- src/BuildToolchains.jl
Should fix errors in https://github.com/JuliaPackaging/Yggdrasil/pull/4734
> [BuildToolchains] Strip trailing whitespace from output of commands

- Artifacts.toml
- src/Rootfs.jl
Includes https://github.com/JuliaPackaging/Yggdrasil/pull/4762 and https://github.com/JuliaPackaging/Yggdrasil/pull/4753/commits/c7bd98f77b6f14b9ac42c78a99d4ef659b83bbf3
> Bump Rootfs to include new Musl build

- Project.toml
- src/Platforms.jl
Using only `-mcpu=generic-armv7-a` causes an error in the assembler with GCC 5:
```console
% julia --compile=min -e 'using BinaryBuilderBase; BinaryBuilderBase.runshell(Platform("armv7l", "linux"); preferred_gcc_version=v"5")'
sandbox:${WORKSPACE} # echo 'int main(){}' | /opt/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -x c - -mcpu=generic-armv7-a
Assembler messages:
Error: unknown cpu `generic-armv7-a'
Error: unrecognized option -mcpu=generic-armv7-a
```
We may have to revise how GCC is compiled for this platform, but this is for
another day.
Ref: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/238#pullrequestreview-943928912
> [Platforms] Restore previous compilation flags for base armv7l architecture

- src/Prefix.jl
- src/Sources.jl
- test/sources.jl
To reproduce the issue, try to run a wizard session based off of the file `https://github.com/ashwani-rathee/io-project/blob/main/gifwrapper/gen/libgifextra.zip?raw=true`.  You eventually get:
```
ArgumentError: '/tmp/jl_geNiLj/JIG6zjMf/srcdir' exists. `force=true` is required to remove '/tmp/jl_geNiLj/JIG6zjMf/srcdir' before copying.
Stacktrace:
[1] checkfor_mv_cp_cptree(src::String, dst::String, txt::String; force::Bool)
@ Base.Filesystem ./file.jl:312
[2] cp(src::String, dst::String; force::Bool, follow_symlinks::Bool)
@ Base.Filesystem ./file.jl:349
[3] cp
@ ./file.jl:349 [inlined]
[4] setup(source::BinaryBuilderBase.SetupSource{FileSource}, target::String, verbose::Bool)
@ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/IKZGk/src/Prefix.jl:309
```
Because the `.zip` file is …
> Fix some issues reported on Slack

- src/Prefix.jl
CC: @Alexander-Barth.  Fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1210.
> [Prefix] Work around the fact `Pkg.add` modifies dependencies in-place

- src/Dependencies.jl
`build_version` is a positional argument, not a keyword one.
> [Dependencies] Clarify docstring of `Dependency`

- src/Platforms.jl
- src/Products.jl
- src/Rootfs.jl
- src/Runner.jl
This adds support for automatically adding the appropriate `-fsanitize=`
flags when the platform includes a `sanitizer` tag. This is particularly
intended for msan, which requires that all .so's in the system are built
using it, but could be useful for other sanitizers also.
There's a couple annoyances. One is that we don't currently actually ship
the sanitizer runtime libraries in our rootfs. Thus, if we want to start
using this, we'd have to add a BuildDependency on LLVMCompilerRT_jll and
manually copy the runtime libraries into place. Not the end of the world,
but certainly a wart.
The other issue is that `platforms_match` (which is defined in Base) of
course currently ignores the `sanitizer` tag. In theory it is possible
to add a custom compare strategy, but since we're specifying the …
> Add support for building sanitizer-enabled jlls

- src/BuildToolchains.jl
- src/Runner.jl
- test/runners.jl
This allows us to consistently define for which platforms we want to use Clang
as default compiler.
Follow up to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/258#discussion_r954091351
> [Runner] Define function `prefer_clang`

- src/Runner.jl
- test/runners.jl
This is to avoid unused argument warnings like in [this build](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=21607&view=logs&jobId=5850b9b5-9a51-573f-7d03-f1fedbd8a7fb&j=5850b9b5-9a51-573f-7d03-f1fedbd8a7fb&t=34cffb34-e22b-5097-6aba-496cb946d943)
> Move -rtlib and friends to linker flags

- src/Runner.jl
- test/runners.jl
This also adds a test similar to the C one but for C++.
Should hopefully fix https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/261#issuecomment-1232268021
I wonder what happens if someone does a cc invocation while linking with the c++ lib.
> Make libstdc++ available at compile time when compiling c++

- src/Rootfs.jl
- test/rootfs.jl
How about this, so then we don't get useless builds, but still have the tags when needed
> Make the platform expansions MSAN aware

- src/Rootfs.jl
- test/rootfs.jl
#271 made `expand_cxxstring_abis` type unstable, so force specialization on it.
> Enforce type stability and test for it

- src/Dependencies.jl
- test/dependencies.jl
Motivated by https://github.com/JuliaParallel/MPI.jl/issues/646
In order for invalidation to happen we need to declare the dependency on the top-level of the file instead of in one of the platform specific wrappers.
> Add the concept of a top-level dependency

- src/Runner.jl
Fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1232
> [Runner] Use `-Wl,--no-insert-timestamp` on Windows, for reproducibility

- Project.toml
- src/Sources.jl
- test/sources.jl
Basically same as https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/940, but in this package.  Fix bug reported by @Seelengrab on Slack.
> [Sources] Consider URLs starting with `git://` as Git repositories

- src/Dependencies.jl
- test/dependencies.jl
Also, deprecate `top_level` with `Dependency`.  Ref: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/275#discussion_r996320261.
> [Dependencies] Allow using `top_level` with `RuntimeDependency`

- src/Runner.jl
- test/runners.jl
> [Runner] Set also minimum SDK version when targeting macOS

- Project.toml
- src/Dependencies.jl
- test/dependencies.jl
First part of fixing https://github.com/JuliaPackaging/Yggdrasil/pull/6417#issuecomment-1476823499.
This was quite a yak-shaving, because while preparing the test I double checked that that new tests would fail without the change introduced here, which of course didn't happen, and realised that the current definition of `==` for `AbstractDependency` wasn't really sound.
Note: https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1273 reduces the need for such conversions, but doesn't entirely eliminate it.  I think it'd be better to try and avoid the conversion completely at a later point.
> [Dependency] Preserve `top_level` when converting `RuntimeDependency` -> `Dependency`

- src/Runner.jl
Tests seem to be failing at the moment on master for an unrelated reason.
> Add defines for gcc and clang that declare we are Windows 10

- Artifacts.toml
Ref: https://github.com/JuliaLang/julia/issues/48187.  @jd-foster found that this was due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105745, after applying the patch to our GCC 12.1 build @tylerjthomas9 reported that the new libgomp made tests of `XGBoost.jl` and `LIBSVM.jl` pass.
Other related issues:
* https://github.com/darktable-org/darktable/issues/11889
* https://github.com/msys2/MINGW-packages/issues/11729
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/6871.
> Update GCC 12.1 build for Windows to include libgomp fix

- Artifacts.toml
Rebuild compiler shards with https://github.com/JuliaPackaging/Yggdrasil/pull/7136
> Upgrade glibc on x86_64 and i686 to v2.17

- Artifacts.toml
- src/Rootfs.jl
- test/rootfs.jl
This bumps the mingw runtime to the 11.0.1 version. mingw + mscvrt doesn't have version constraints because it's a statically linked runtime that links to  msvcrt.dll which is always there
> Add new rebuilt mingw shards

- src/Runner.jl
Tested with
`test.c`:
```c
#include <dlfcn.h>
void foo() {
dlclose(dlopen("libc.so", RTLD_LOCAL | RTLD_LAZY));
}
```
`main.c`:
```c
void foo();
int main(void) {
foo();
return 0;
}
```
`Makefile`:
```make
main: main.c libtest.so
SUPER_VERBOSE=1 cc -L. -o main main.c -ltest
libtest.so: test.c
SUPER_VERBOSE=1 cc -shared -o libtest.so test.c -ldl
```
Before this PR:
```console
% julia --compile=min -e 'using BinaryBuilderBase; BinaryBuilderBase.runshell(Platform("powerpc64le", "linux"); preferred_gcc_version = v"6")'
sandbox:${WORKSPACE} # make -B
SUPER_VERBOSE=1 cc -shared -o libtest.so test.c -ldl
ccache /opt/powerpc64le-linux-gnu/bin/powerpc64le-linux-gnu-gcc -D_GLIBCXX_USE_CXX11_ABI=1 -frandom-seed=0x9847abb0 -L/opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/lib64 …
```
> [Runner] Fix inclusion of `lib64` for PowerPC64 with GCC 6

- src/Runner.jl
- test/rootfs.jl
- test/runners.jl
This switches clang to use lld when the clang version is 16 or above and the GCC version is 5 or above, It passes the commented out version of the test locally but given the issues we are seeing I'leaving it commented out for now.
The main goal of this is so that clang doesn't complain about very new linker features that the shipped binutils might not have.
> Default clang to use lld on specific conditions

- .github/workflows/ci.yml
- test/runners.jl
Alternative to #321.  Not a great solution, but at least we can get _some_ tests to actually run.
Close #321.
> [CI] Do not run full tests when using unpacked shards

- src/BuildToolchains.jl
- src/Runner.jl
- test/runners.jl
Fixes https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/349. Though -fuse-ld=lld is only available to GCC9 and up IIRC.
Also supercedes https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/342
> Fixup lld code even more and make sure gcc can use it

- src/BuildToolchains.jl
- src/Runner.jl
Meson tries really hard to do it wrong.
Also note for the future `-fuse-ld` behaves very differently between `gcc` and `clang`. GCC only wants a linker name, while clang understands a full path and one with platform specific handling. Also gcc calls it `bfd` while clang wants `ld`
> Babysit meson so it doesn't do the wrong thing

- Project.toml
- src/Runner.jl
- test/runners.jl
I need to do more testing (hence opening as draft), but this might be sufficient to let users set `clang_use_lld` as keyword argument to `BinaryBuilder.build_tarballs`, so that they can easily opt-out of it.
> [Runner] Make `clang_use_lld` a keyword argument

- .github/workflows/ci.yml
We can't cache the artifacts when running the main tests because that'd require over 10 GiB, which is the maximum GHA can handle, so at least we cache stuff for the docs.
> [CI] Use `julia-actions/cache` workflow only for the docs

- Artifacts.toml
Updates to the compiler shards for GCC to contain patches to fix building with AMX instructions, and build with the new Mingw 11 toolchain.
The GCC 11 build was just everything, since the glib version also was bumped since the last rebuild, so I didn't want to sort out the affected platforms. GCC 12 and 13 were targetted only at Windows because the needed patches and Mingw updates only affected the Windows platform.
> Update GCC compiler shards

- src/Runner.jl
Trying to build https://github.com/JuliaPackaging/Yggdrasil/pull/7872 on `master` for `x86_64-linux-gnu-cxx11-sanitize+memory` (see https://github.com/JuliaPackaging/Yggdrasil/pull/7872#issuecomment-1913141689):
```console
sandbox:${WORKSPACE}/srcdir/gmp-6.3.0 # echo 'int main (void) { return 0; }' | SUPER_VERBOSE=1 c++ -x c++ - -g -O2
ccache /opt/x86_64-linux-musl/bin/clang++ -target x86_64-linux-gnu --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root -D_GLIBCXX_USE_CXX11_ABI=1 -stdlib=libstdc++ -march=x86-64 -mtune=generic -fsanitize=memory -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/6.1.0 -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/6.1.0/x86_64-linux-gnu -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/6.1.0/backward -isystem …
```
> [Runner] Fix MSAN C++ compiler with LLVM 13

- Artifacts.toml
See https://github.com/JuliaPackaging/Yggdrasil/pull/8205
> Update GCC 13 shards for `libgomp` fix

- Artifacts.toml
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/8412
> [RootFS] Update Rust to v1.77.1

- src/DockerRunner.jl
Fixes DockerRunner for macOS >= 13 wrt. xattrs added by macOS which Docker does not like.
> Added fix for DockerRunner on macOS >= 13 wrt. xattrs

- Artifacts.toml
Counterpart of https://github.com/JuliaPackaging/Yggdrasil/pull/9162.
@giordano Anything else I need to do? FWIW, I had to do the `Artifacts.toml` changes manually, for some reason `--deploy` didn't pick up my `dev`ed BinaryBuilderBase.jl.
> Add bootstrap artifacts for LLVM 14, 15 and 17.

- src/Runner.jl
- test/runners.jl
This makes it clearer, that Binary builder actually doesn't allow unsafe flags and errors.
> improve error message for unsafe flags

- test/runners.jl
The issue we were having before on GitHub-hosted Actions runners appears to have been fixed.
Close #347.
> Mark broken test as passing

- test/runners.jl
Ref #395.  At least we should have green CI.
> Skip Rust tests with unprivileged runners and unpacked shards

- Project.toml
- src/Rootfs.jl
- test/rootfs.jl
This exposes two new keyword arguments for finding the shards: `preferred_rust_version` and `preferred_go_version`, which will specify the version of the toolchain to use. Note these are implemented as strict requests for now, but I kept the "preferred" name to match the gcc and llvm arguments.
I know the Rust toolchain is probably fine as a strict request, but I don't know about Go's commitment to compatibility across compiler versions.
> Allow specifying a Rust and Go toolchain version for the build

- Project.toml
- src/Rootfs.jl
Rust requires glibc 2.17, which we only have with GCC >5. This at least fixes the x86_64 failure seen in the BinaryBuilder CI https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1358, which is giving the error:
```
/rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/pal/unix/stack_overflow.rs:270: undefined reference to `getauxval'
/rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/pal/unix/stack_overflow.rs:270: undefined reference to `getauxval'
collect2: error: ld returned 1 exit status
```
> Always use GCC >5 when building Rust

- Artifacts.toml
- Project.toml
- src/Rootfs.jl
We've had a few problems with GCC 12 on riscv64 (missing `riscv_vector.h` header file, broken support for atomics) that we're often forced to use GCC 13.  Let's always use GCC 13 at minimum and live happier.
Once we get GCC 14 in we may bump the minimum riscv64 GCC toolchain to that version, because it introduces better support for the version 1.0 of the vector extension, important for OpenBLAS and other software.
> [RootFS] Use GCC 13+ for riscv64

- src/Runner.jl
Ref https://github.com/JuliaPackaging/Yggdrasil/pull/10204#issuecomment-2573845355.
> [Runner] Work around wrong path of compiler libraries for riscv64

- .github/workflows/ci.yml
- Artifacts.toml
- Project.toml
- src/Rootfs.jl
- src/Runner.jl
- test/rootfs.jl
GCC 14 has support for the RISV-V Vector Extension 1.0 (RVV1.0), which is important for packages like OpenBLAS.  `riscv64` is still niche enough that it's OK to use a more recent, but also more capable, version of GCC as default one.
Companion PR to https://github.com/JuliaPackaging/Yggdrasil/pull/10132.
Fix #398.
> [Rootfs] Add GCC 14.2 and make it default for riscv64

- Project.toml
- src/Runner.jl
- test/runners.jl
The current order of header search paths of clang targeting platforms different than macOS and FreeBSD makes it somewhat broken:
```console
% julia -e 'using BinaryBuilderBase; BinaryBuilderBase.runshell(Platform("aarch64", "linux"))'
sandbox:${WORKSPACE} # echo -e '#include <cstdint>\nint main(){return 0;}'|clang -x c++ - -H -o /dev/null
. /opt/aarch64-linux-gnu/aarch64-linux-gnu/include/c++/4.8.5/cstdint
.. /opt/aarch64-linux-gnu/aarch64-linux-gnu/include/c++/4.8.5/aarch64-linux-gnu/bits/c++config.h
... /opt/aarch64-linux-gnu/aarch64-linux-gnu/include/c++/4.8.5/aarch64-linux-gnu/bits/os_defines.h
.... /opt/aarch64-linux-gnu/aarch64-linux-gnu/sys-root/usr/include/features.h
..... /opt/aarch64-linux-gnu/aarch64-linux-gnu/sys-root/usr/include/stdc-predef.h
..... …
```
> [Runner] Adjust clang flags to make it work slightly better on Linux

- Project.toml
- src/Runner.jl
I believe this is needed for https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1364.  This also addresses https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/5#issuecomment-1765420586
> [Runner] Move some functions outside of giant `generate_compiler_wrappers!`

- test/dependencies.jl
The test being added here triggers https://github.com/JuliaPackaging/Yggdrasil/pull/10524#issuecomment-2657162519 in Julia v1.9-11 and https://github.com/JuliaPackaging/Yggdrasil/pull/10524#issuecomment-2660939179 on current `master` (https://github.com/JuliaLang/julia/commit/c93e28e8a2437c906f2c0dd21c200dde690a0fb2).  Adding the test here as a reference of an operation we want to make sure works correctly.
> Add a test for installing a dependency with a specific version number

- Artifacts.toml
- Project.toml
- src/Rootfs.jl
- test/rootfs.jl
Companion to https://github.com/JuliaPackaging/Yggdrasil/pull/10402
To do:
> Update FreeBSD versions to 13.4 on x86-64 and 14.1 on AArch64

- Project.toml
- src/BuildToolchains.jl
RISCV installs place the libraries inside a folder that is named after the ABI, so we need to prompt CMake to search there. This should fix the toolchain issue discussed in https://github.com/JuliaPackaging/Yggdrasil/pull/10922#discussion_r2029505751.
cc @eschnett @giordano
> RISCV: Add CMake variable to set the system library directory

- src/Runner.jl
- test/rootfs.jl
Updated `xcrun` executable to handle `--sdk`, `--show-sdk-path` and `--show-sdk-version`.
Also, added `SDKROOT` env. var.
Usages of `xcrun --show-sdk-path` etc.:
* https://github.com/JuliaPackaging/Yggdrasil/pull/7507
* https://github.com/JuliaPackaging/Yggdrasil/pull/9785
* https://github.com/JuliaPackaging/Yggdrasil/pull/9797
```sh
$ xcrun echo foo
foo
$ xcrun --show-sdk-path
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root
$ xcrun --show-sdk-version
10.12
$ xcrun --show-sdk-path --show-sdk-version
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root
10.12
$ xcrun --show-sdk-path --show-sdk-version echo foo
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root
10.12
foo
$ xcrun --sdk /opt/$target/$target/sys-root --show-sdk-path --show-sdk-version echo foo …
```
> [Runner] Updated xcrun executable to handle a few arguments

- src/Rootfs.jl
I was very confused why https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/427 didn't take for me locally - turns out we cache these at precompile time. We have a mechanism for this situation, so let's use it.
> Re-precompile BinaryBuilderBase if Artifacts.toml changes

- src/Runner.jl
- test/runners.jl
This was causing errors when compiling with
`-Werror=unused-command-line-argument`.
Close #426.
> [Runner] Set linker min macos version flag only when linking

- Artifacts.toml
- Project.toml
- src/Rootfs.jl
- src/Runner.jl
- test/rootfs.jl
- test/runners.jl
This is a preliminary implementation of OCaml compiler support in BinaryBuilder.
Dependent on https://github.com/JuliaPackaging/Yggdrasil/pull/11146
> Implement preliminary OCaml support

- Project.toml
- deps/.gitignore
- src/BinaryBuilderBase.jl
I've been wanting to make this change for years.  BinaryBuilder2 does already something along these lines: https://github.com/JuliaPackaging/BinaryBuilder2.jl/blob/8243bd31c94f542b44c254d9c729ad133cc990b0/BinaryBuilderSources.jl/src/BinaryBuilderSources.jl#L138-L140
> Put default storage cache in a scratch space

- src/Runner.jl
- test/runners.jl
As discovered in https://github.com/JuliaPackaging/Yggdrasil/pull/12004, `--build-id=sha1` doesn't seem to be supported with lld on windows.
Also, to make reproducible set `-Wl,--no-insert-timestamp` when using clang (we already do this for gcc).
> [Runner] Fix build id with lld on windows
